#!/bin/bash
#thresholds={"0.1" "0.2" "0.3" "0.4"}
thresholds=(0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9)
for threshold in ${thresholds[*]};do
    
# ../server/TCBackup_server -p & 
#   sleep 3; 
    ./rewrite_test $threshold 
#   kill -9 $(pidof TCBackup_server)
    cd ..
    ./rebuild
    ./clear
    cd client
    print $threshold
done
